return {
	['Default'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['OpenPosition'] = UDim2.fromScale(.5, .5),
		['ClosePosition'] = UDim2.fromScale(.5, 1.5),
	},

	['Wheel'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['OpenPosition'] = UDim2.fromScale(.5, .5),
		['ClosePosition'] = UDim2.fromScale(.5, 3),
	},

	['CarInfo'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['IgnoreVisible'] = true,
		['OpenPosition'] = UDim2.fromScale(0.6, 0.115),
		['ClosePosition'] = UDim2.fromScale(1, 0.115),
	},

	['TeleportBack'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['OpenPosition'] = UDim2.fromScale(.5, 1),
		['ClosePosition'] = UDim2.fromScale(.5, 3),
	},
}
