return {
	['Default'] = {
		['Speed'] = 45,
		['OnEnterScale'] = 1.1,
		['OnLeaveScale'] = 1,
		['Velocity'] = -10,
		['Scope'] = 'PlayInterfaceSound',
		['ClickSound'] = 'Click',
		['HoverSound'] = 'Hover',
	},
	
	['LongButton'] = {
		['Speed'] = 20,
		['OnEnterScale'] = 1.05,
		['OnLeaveScale'] = 1,
		['Velocity'] = -5,
		['Scope'] = 'PlayInterfaceSound',
		['ClickSound'] = 'Click',
		['HoverSound'] = 'Hover',
	},
}
