local module = require(script.Parent:FindFirstChild(".pesde"):FindFirstChild("lm-loleris_profilestore@1.0.3"):FindFirstChild("profilestore"))
export type JSONAcceptable  = module.JSONAcceptable 
export type Profile<T> = module.Profile<T>
export type VersionQuery<T> = module.VersionQuery<T>
export type ProfileStore<T> = module.ProfileStore<T>
export type ProfileStoreModule  = module.ProfileStoreModule 
return module