local module = require("./../../../../../../luau_packages/.pesde/0x5eal+unzip/0.2.0/unzip/lib")
export type ZipEntry  = module.ZipEntry 
export type MadeByOS  = module.MadeByOS 
export type CompressionMethod  = module.CompressionMethod 
export type UnixMode  = module.UnixMode 
export type ZipReader  = module.ZipReader 
export type EocdRecord  = module.EocdRecord 
export type ZipStatistics  = module.ZipStatistics 
return module