return 
	{
		['Equip'] = 
		{
			Name = 'EquipFists';
			Priority = Enum.AnimationPriority.Action.Name;
			_Name = 'EquipFists';

			Settings = 
			{
				Speed = 1;
				Weight = 1;
				FadeTime = .1;
			}
		};
		['Idle'] = 
		{
			Name = 'Idle';
			Priority = Enum.AnimationPriority.Idle.Name;
			_Name = 'IdleFists';

			Settings = 
			{
				Speed = 1;
				Weight = 1;
				FadeTime = .1;
			}
		};
		['Walk'] = 
		{
			Name = 'Walk';
			Priority = Enum.AnimationPriority.Movement.Name;
			_Name = 'WalkFists';

			Settings = 
			{
				Speed = 1;
				Weight = 1;
				FadeTime = .1;
			}
		}
	}