local module = require("./../../../../jiwonz+pathfs/0.6.0/pathfs/src/lib")
export type DirectoryPath  = module.DirectoryPath 
export type FilePath  = module.FilePath 
export type Metadata  = module.Metadata 
export type MetadataKind  = module.MetadataKind 
export type MetadataPermissions  = module.MetadataPermissions 
export type WriteOptions  = module.WriteOptions 
export type Components  = module.Components 
export type Path  = module.Path 
export type AsPath  = module.AsPath 
export type Component  = module.Component 
export type DirEntry  = module.DirEntry 
return module