return {
	['Default'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['OpenSize'] = UDim2.fromScale(.5, .5),
		['CloseSize'] = UDim2.fromScale(.5, 1),
	},
	['Notify'] = {
		['Speed'] = 6,
        ['Time'] = .2,
		['OpenSize'] = UDim2.fromScale(0.135, 0.68),
		['CloseSize'] = UDim2.fromScale(0.07, 0.2),
	},
	['CarFrame'] = {
		['Speed'] = 4,
        ['Time'] = 1,
		['IgnoreVisible'] = true,
		['OpenSize'] = UDim2.fromScale(0.586, 0.874), --{0.586, 0},{0.874, 0}
		['CloseSize'] = UDim2.fromScale(0.965, 0.874), --{0.965, 0},{0.874, 0}
	},
}
